### ISSUE TITLE
Deploy to Heroku error

### ISSUE THREAD

**Issue by yannbertrand** [Weetbix/facebot#19] opened 2017-04-12 10:10 UTC
I tried to deploy the app to Heroku using the button in the README.

This is the log I have inside Heroku

```
017-04-12T10:08:20.042923+00:00 app[worker.1]: npm ERR! Failed at the facebot@0.0.8 start script 'node bin/run_postgres.js'.

2017-04-12T10:08:20.043207+00:00 app[worker.1]: npm ERR! not with npm itself.

2017-04-12T10:08:20.043049+00:00 app[worker.1]: npm ERR! This is most likely a problem with the facebot package,

2017-04-12T10:08:20.043442+00:00 app[worker.1]: npm ERR!     node bin/run_postgres.js

2017-04-12T10:08:20.043876+00:00 app[worker.1]: npm ERR!     npm owner ls facebot

2017-04-12T10:08:20.043327+00:00 app[worker.1]: npm ERR! Tell the author that this fails on your system:

2017-04-12T10:08:20.043688+00:00 app[worker.1]: npm ERR! You can get their info via:

2017-04-12T10:08:20.046829+00:00 app[worker.1]: 

2017-04-12T10:08:20.044001+00:00 app[worker.1]: npm ERR! There is likely additional logging output above.

2017-04-12T10:08:20.047143+00:00 app[worker.1]: npm ERR!     /app/npm-debug.log

2017-04-12T10:08:20.047037+00:00 app[worker.1]: npm ERR! Please include the following file with any support request:
```

**Comment by flocca** [comment] 2017-04-14 07:06
Same here.

The problem is emoji.init_env();

```
2017-04-14T07:04:54.237748+00:00 app[worker.1]: /app/lib/facebot.js:27
2017-04-14T07:04:54.237768+00:00 app[worker.1]:     emoji.init_env();
2017-04-14T07:04:54.237769+00:00 app[worker.1]:           ^
2017-04-14T07:04:54.237770+00:00 app[worker.1]: 
2017-04-14T07:04:54.237771+00:00 app[worker.1]: TypeError: emoji.init_env is not a function
2017-04-14T07:04:54.237772+00:00 app[worker.1]:     at new Constructor (/app/lib/facebot.js:27:11)
2017-04-14T07:04:54.237773+00:00 app[worker.1]:     at Object.<anonymous> (/app/bin/run_postgres.js:101:15)
2017-04-14T07:04:54.237774+00:00 app[worker.1]:     at Module._compile (module.js:435:26)
2017-04-14T07:04:54.237774+00:00 app[worker.1]:     at Object.Module._extensions..js (module.js:442:10)
2017-04-14T07:04:54.237775+00:00 app[worker.1]:     at Module.load (module.js:356:32)
2017-04-14T07:04:54.237776+00:00 app[worker.1]:     at Function.Module._load (module.js:313:12)
2017-04-14T07:04:54.237776+00:00 app[worker.1]:     at Function.Module.runMain (module.js:467:10)
2017-04-14T07:04:54.237777+00:00 app[worker.1]:     at startup (node.js:136:18)
2017-04-14T07:04:54.237778+00:00 app[worker.1]:     at node.js:963:3
```

**Comment by mitchcapper** [comment] 2017-04-14 13:55
You need to pull the latest GitHub version as commit 34e951763bbf74a75c789cf22fb6cc3280fdfd34 fixed it.  May need to manually merge into the deploy branch.

**Comment by yannbertrand** [comment] 2017-04-14 14:14
Well, I just clicked the link on the master branch so this commit should have been included

**Comment by mitchcapper** [comment] 2017-04-14 14:19
It depends there is a deploy branch changes have not been merged into yet and that is the default:  https://heroku.com/deploy?template=https://github.com/Weetbix/facebot/tree/deploy  see.   
We are currently working to fix some items up with facebot.  I would assume that branch will be updated soon.   

Try this (note I did not test just updated deploy with master):
https://heroku.com/deploy?template=https://github.com/MitchCapper/facebot/tree/deploy_updated

Again the official one will be updated once the rest of the code/cleanup updates are done I would assume.

**Comment by yannbertrand** [comment] 2017-04-14 14:30
```
2017-04-14T14:23:48.246102+00:00 app[worker.1]: /app/lib/util.js:6
2017-04-14T14:23:48.246123+00:00 app[worker.1]: async function getFBUserInfoByID(api, id) {
2017-04-14T14:23:48.246125+00:00 app[worker.1]:       ^^^^^^^^
2017-04-14T14:23:48.246125+00:00 app[worker.1]: 
2017-04-14T14:23:48.246126+00:00 app[worker.1]: SyntaxError: Unexpected token function
2017-04-14T14:23:48.246127+00:00 app[worker.1]:     at exports.runInThisContext (vm.js:53:16)
2017-04-14T14:23:48.246127+00:00 app[worker.1]:     at Module._compile (module.js:414:25)
2017-04-14T14:23:48.246128+00:00 app[worker.1]:     at Object.Module._extensions..js (module.js:442:10)
2017-04-14T14:23:48.246129+00:00 app[worker.1]:     at Module.load (module.js:356:32)
2017-04-14T14:23:48.246130+00:00 app[worker.1]:     at Function.Module._load (module.js:313:12)
2017-04-14T14:23:48.246130+00:00 app[worker.1]:     at Module.require (module.js:366:17)
2017-04-14T14:23:48.246131+00:00 app[worker.1]:     at require (module.js:385:17)
2017-04-14T14:23:48.246131+00:00 app[worker.1]:     at Object.<anonymous> (/app/lib/facebot.js:8:14)
2017-04-14T14:23:48.246132+00:00 app[worker.1]:     at Module._compile (module.js:435:26)
2017-04-14T14:23:48.246133+00:00 app[worker.1]:     at Object.Module._extensions..js (module.js:442:10)
2017-04-14T14:23:48.246134+00:00 app[worker.1]:     at Module.load (module.js:356:32)
2017-04-14T14:23:48.246134+00:00 app[worker.1]:     at Function.Module._load (module.js:313:12)
2017-04-14T14:23:48.246135+00:00 app[worker.1]:     at Module.require (module.js:366:17)
2017-04-14T14:23:48.246135+00:00 app[worker.1]:     at require (module.js:385:17)
2017-04-14T14:23:48.246136+00:00 app[worker.1]:     at Object.<anonymous> (/app/bin/run_postgres.js:7:15)
2017-04-14T14:23:48.246137+00:00 app[worker.1]:     at Module._compile (module.js:435:26)
```

Please do not add this "Deploy to Heroku" in the master branch README before it's ready :smile: 

Thanks for your job anyway, I'll just wait for the next release :wink:

**Comment by mitchcapper** [comment] 2017-04-14 14:37
Deploy to heroku worked just fine previously, the problem is a library got updated and it is pegged against head which broke it.   Yeah the new async seems more up to date than heroku.  Technically the emoji fix is a two line change, but due to facebook API updates it will be better for you to wait for an official release for everything to work.

**Comment by mitchcapper** [comment] 2017-04-14 14:53
There is one more test you can do, I updated the engine, I don't have heroku to test with but you can give it another shot if you want.  Otherwise next release is probably not too far out.

**Comment by Weetbix** [comment] 2018-07-10 23:08
Master is updated and tested to work locally and on heroku now 👍

**Closed as completed by Weetbix** 2018-07-10 23:08 UTC
